import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
import { PRODUCTS } from '../app.js';

await writeFile(new URL('../search-catalog.json', import.meta.url), JSON.stringify(PRODUCTS, null, 2) + '\n');

// Keep the shop usable when opened directly from disk, where module imports
// are blocked. Edit the source modules, then regenerate with npm run build.
await build({
  entryPoints: ['shop.js'],
  outfile: 'shop.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '// Generated by npm run build. Edit app.js, shop-state.js, or shop.js instead.' },
});

await build({
  entryPoints: ['app.js'],
  outfile: 'app.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '// Generated by npm run build. Edit app.js or search.js instead.' },
});
