import { build } from 'esbuild';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { PRODUCTS } from '../app.js';
import { DEFAULT_PRODUCT_ID, renderProductPage } from '../product-content.js';
import { STORE_CONTACT, ORDER_CHANNELS } from '../store-contact.js';

const root = new URL('../', import.meta.url);
for (const file of (await readdir(root)).filter(name => name.endsWith('.html'))) {
  const path = new URL(file, root);
  const source = await readFile(path, 'utf8');
  const links = `<div class="store-contact-links">${STORE_CONTACT.email ? `<a href="mailto:${STORE_CONTACT.email}">Email us ↗</a>` : ''}<a href="${STORE_CONTACT.facebook}" target="_blank" rel="noopener noreferrer">Contact on Facebook ↗</a></div>`;
  await writeFile(path, source.replace(/<!-- STORE_CONTACT_START -->[\s\S]*?<!-- STORE_CONTACT_END -->/, `<!-- STORE_CONTACT_START -->${links}<!-- STORE_CONTACT_END -->`).replace(/<p class="order-summary-note">[\s\S]*?<\/p>/, `<p class="order-summary-note">Order by ${ORDER_CHANNELS}. Our team will confirm availability, delivery, and payment details.</p>`));
}

const productPage = new URL('../product.html', import.meta.url);
const page = await readFile(productPage, 'utf8');
const defaultProduct = PRODUCTS.find(p => p.id === DEFAULT_PRODUCT_ID);
await writeFile(productPage, page.replace(/<main id="main">[\s\S]*?<\/main>/, `<main id="main">${renderProductPage(defaultProduct)}<noscript><p class="section-shell">Enable JavaScript to select a product, explore image details, and add pieces to your bag. <a href="shop.html">Browse the shop</a>.</p></noscript></main>`)
  .replace(/<title>[\s\S]*?<\/title>/, `<title>${defaultProduct.name} — SHINE THROUGH</title>`)
  .replace(/<meta name="description" content="[^"]*"\s*\/>/, `<meta name="description" content="${defaultProduct.description}" />`));

await build({
  entryPoints: ['product.js'],
  outfile: 'product.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '// Generated by npm run build. Edit product.js, product-content.js, or app.js instead.' },
});

await writeFile(new URL('../search-catalog.json', import.meta.url), JSON.stringify(PRODUCTS, null, 2) + '\n');

// Keep the shop usable when opened directly from disk, where module imports
// are blocked. Edit the source modules, then regenerate with npm run build.
await build({
  entryPoints: ['shop.js'],
  outfile: 'shop.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '// Generated by npm run build. Edit app.js, shop-state.js, or shop.js instead.' },
});

await build({
  entryPoints: ['app.js'],
  outfile: 'app.bundle.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  banner: { js: '// Generated by npm run build. Edit app.js or search.js instead.' },
});

